# Generated by Django 2.1.3 on 2018-12-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20181208_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于无法作为菜单的URL，可以为其选择一个可以作为菜单的权限，那么访问时，则默认选中此权限', limit_choices_to={'menu__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patents', to='rbac.Permission', verbose_name='默认选中权限'),
        ),
    ]
